# Generated by Django 5.1.1 on 2024-09-19 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_ai', models.BooleanField(default=False)),
                ('extra_data', models.JSONField()),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_messages', to='user.user')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_messages', to='user.user')),
            ],
        ),
    ]
