# Generated by Django 5.1.1 on 2024-10-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='create_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
