# Generated by Django 5.1.1 on 2024-11-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='roles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
