# Generated by Django 5.1.1 on 2024-09-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviceresponse',
            table='service_response',
        ),
    ]
