# Generated by Django 5.1.1 on 2024-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_serviceresponse_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPTService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('discount', models.IntegerField(default=0)),
                ('number_of_month', models.IntegerField()),
                ('cost_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'nonpt_service',
            },
        ),
        migrations.CreateModel(
            name='PTService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('discount', models.IntegerField(default=0)),
                ('number_of_session', models.IntegerField()),
                ('session_duration', models.IntegerField()),
                ('cost_per_session', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_period', models.IntegerField(default=45)),
            ],
            options={
                'db_table': 'pt_service',
            },
        ),
    ]
