# Generated by Django 5.1.1 on 2024-10-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_nonptservice_customer_ptservice_coach_and_more'),
        ('user_profile', '0005_remove_coachprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonptservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_nonptservices', to='user_profile.customerprofile'),
        ),
        migrations.AlterField(
            model_name='ptservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_ptservices', to='user_profile.customerprofile'),
        ),
    ]
