# Generated by Django 5.1.1 on 2024-10-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_nonptservice_customer_alter_ptservice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonptservice',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ptservice',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
