# Generated by Django 5.1.1 on 2024-10-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_nonptservice_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonptservice',
            name='name',
            field=models.CharField(default='Gói tập luyện ...', max_length=256),
        ),
        migrations.AlterField(
            model_name='ptservice',
            name='name',
            field=models.CharField(default='Gói tập luyện ...', max_length=256),
        ),
    ]
