# Generated by Django 5.1.1 on 2024-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_nonptservice_customer_remove_ptservice_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresponse',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
