# Generated by Django 5.1.1 on 2024-10-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_serviceresponse_coach'),
        ('user_profile', '0008_customerprofile_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresponse',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='user_profile.coachprofile'),
        ),
        migrations.AlterField(
            model_name='serviceresponse',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='user_profile.customerprofile'),
        ),
    ]
