# Generated by Django 5.1.1 on 2024-10-18 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_serviceresponse_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresponse',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
