# Generated by Django 5.1.1 on 2024-10-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_serviceresponse_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonptservice',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='nonptservice',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='ptservice',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='ptservice',
            name='start_date',
        ),
    ]
