# Generated by Django 5.1.1 on 2024-10-23 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_nonptservice_expire_date_and_more'),
        ('user_profile', '0010_customerprofile_body_fat_customerprofile_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_contracts', to='user_profile.coachprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contracts', to='user_profile.customerprofile')),
                ('nonptservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.nonptservice')),
                ('ptservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ptservice')),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
