# Generated by Django 5.1.1 on 2024-10-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
