# Generated by Django 5.1.1 on 2024-10-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_contract'),
        ('user_profile', '0011_remove_coachprofile_undertaken_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='customer',
        ),
        migrations.AddField(
            model_name='contract',
            name='coach',
            field=models.ManyToManyField(blank=True, null=True, related_name='coach_contracts', to='user_profile.coachprofile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_contracts', to='user_profile.customerprofile'),
        ),
    ]
