# Generated by Django 5.1.1 on 2024-10-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_remove_contract_coach_remove_contract_customer_and_more'),
        ('user_profile', '0011_remove_coachprofile_undertaken_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='coach',
            field=models.ManyToManyField(related_name='coach_contracts', to='user_profile.coachprofile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ManyToManyField(related_name='customer_contracts', to='user_profile.customerprofile'),
        ),
    ]
