# Generated by Django 5.1.1 on 2024-10-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_remove_contract_coach_remove_contract_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='used_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
