# Generated by Django 5.1.1 on 2024-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_contract_is_purchased_contract_used_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptservice',
            name='number_of_session',
        ),
        migrations.AddField(
            model_name='contract',
            name='number_of_session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
