# Generated by Django 5.1.1 on 2024-11-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_remove_ptservice_number_of_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonptservice',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonptservice',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptservice',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptservice',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
