# Generated by Django 5.1.1 on 2024-09-19 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('repetitions', models.CharField(max_length=255)),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('extra_data', models.JSONField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_workout_goal', to='user.user')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('details', models.JSONField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_on', to='user.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('overview', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_coach', to='user.user')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='workout.exercise')),
            ],
        ),
    ]
