# Generated by Django 5.1.1 on 2024-09-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='exercise',
        ),
        migrations.AlterModelTable(
            name='workoutgoal',
            table='workout_goal',
        ),
        migrations.AlterModelTable(
            name='workoutplan',
            table='workout_plan',
        ),
        migrations.AlterModelTable(
            name='workoutschedule',
            table='workout_schedule',
        ),
    ]
