# Generated by Django 5.1.1 on 2024-10-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_nonptservice_customer_remove_ptservice_coach_and_more'),
        ('workout', '0003_remove_workoutplan_coach_remove_workoutplan_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='nonptservice_details',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='ptservice_details',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='nonptservice_details',
            field=models.ManyToManyField(blank=True, null=True, to='service.nonptservice'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ptservice_details',
            field=models.ManyToManyField(blank=True, null=True, to='service.ptservice'),
        ),
    ]
