# Generated by Django 5.1.1 on 2024-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_nonptservice_customer_remove_ptservice_coach_and_more'),
        ('workout', '0004_remove_workoutplan_nonptservice_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='nonptservice_details',
            field=models.ManyToManyField(to='service.nonptservice'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='ptservice_details',
            field=models.ManyToManyField(to='service.ptservice'),
        ),
    ]
