# Generated by Django 5.1.1 on 2024-10-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_workoutplan_nonptservice_details_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
