# Generated by Django 5.1.1 on 2024-10-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_remove_workoutschedule_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
    ]
