# Generated by Django 5.1.1 on 2024-10-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_exercise_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutgoal',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='workoutgoal',
            name='customer',
        ),
        migrations.AddField(
            model_name='workoutgoal',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutgoal',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutgoal',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutgoal',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
