# Generated by Django 5.1.1 on 2024-10-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_alter_exercise_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutSchedule',
        ),
    ]
