# Generated by Django 5.1.1 on 2024-10-28 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_remove_coachprofile_undertaken_services_and_more'),
        ('workout', '0012_workoutschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_schedules', to='user_profile.coachprofile'),
        ),
        migrations.AlterField(
            model_name='workoutschedule',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_schedules', to='user_profile.customerprofile'),
        ),
    ]
