# Generated by Django 5.1.1 on 2024-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_alter_workoutschedule_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
