# Generated by Django 5.1.1 on 2024-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_exercise_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ManyToManyField(to='workout.category'),
        ),
    ]
