# Generated by Django 5.1.1 on 2024-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0015_category_remove_exercise_category_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rest_period',
            field=models.IntegerField(default=45),
        ),
    ]
