# Generated by Django 5.1.1 on 2024-10-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0016_exercise_rest_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='category',
            new_name='categories',
        ),
    ]
