# Generated by Django 5.1.1 on 2024-11-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0017_rename_category_exercise_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
