# Generated by Django 5.1.1 on 2024-11-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_customerprofile_health_condition'),
        ('workout', '0020_remove_workoutschedule_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_schedules', to='user_profile.customerprofile'),
        ),
    ]
