# Generated by Django 5.1.1 on 2024-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0021_alter_workoutschedule_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='embedded_video_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
