# Generated by Django 5.1.1 on 2024-11-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0024_workoutgoal_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
