# Generated by Django 5.1.1 on 2024-11-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0025_workoutschedule_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutschedule',
            old_name='is_done',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workoutschedule',
            name='training_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.trainingplan'),
        ),
    ]
