# Generated by Django 5.1.1 on 2024-09-19 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('gender', models.IntegerField()),
                ('birthday', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('start_date', models.DateField()),
                ('extra_data', models.JSONField()),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('gender', models.IntegerField()),
                ('birthday', models.DateField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
