# Generated by Django 5.1.1 on 2024-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_coachprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
