# Generated by Django 5.1.1 on 2024-10-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_coachprofile_table_alter_customerprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone',
        ),
    ]
