# Generated by Django 5.1.1 on 2024-10-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_nonptservice_customer_remove_ptservice_coach_and_more'),
        ('user_profile', '0005_remove_coachprofile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='undertaken_services',
            field=models.ManyToManyField(blank=True, null=True, to='service.ptservice'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='registered_nonptservices',
            field=models.ManyToManyField(related_name='nonpt_customers', to='service.nonptservice'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='registered_ptservices',
            field=models.ManyToManyField(related_name='pt_customers', to='service.ptservice'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
