# Generated by Django 5.1.1 on 2024-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_nonptservice_customer_remove_ptservice_coach_and_more'),
        ('user_profile', '0006_coachprofile_undertaken_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='undertaken_services',
            field=models.ManyToManyField(to='service.ptservice'),
        ),
    ]
