# Generated by Django 5.1.1 on 2024-10-19 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_customerprofile_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
