# Generated by Django 5.1.1 on 2024-10-20 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_coachprofile_extra_data_and_more'),
        ('workout', '0009_remove_workoutgoal_coach_remove_workoutgoal_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='workout_goal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutgoal'),
        ),
    ]
