# Generated by Django 5.1.1 on 2024-10-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_customerprofile_body_fat_customerprofile_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='undertaken_services',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='registered_nonptservices',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='registered_ptservices',
        ),
    ]
