# Generated by Django 5.1.1 on 2024-11-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_remove_coachprofile_undertaken_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='health_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
