# Generated by Django 5.1.1 on 2024-11-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_customerprofile_health_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='experiences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
