# Generated by Django 5.1.1 on 2024-09-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permission',
            new_name='permissions',
        ),
    ]
