# Generated by Django 5.1.1 on 2024-10-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetpassword',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userresetpassword',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
