# Generated by Django 5.1.1 on 2024-10-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userresetpassword_code_alter_userresetpassword_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetpassword',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
