# Generated by Django 5.1.1 on 2024-10-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userresetpassword_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, upload_to='media/avatars/'),
        ),
    ]
